name: CICD
on:
  push:
    branches: [Master]
jobs: 
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: CheckOut Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurim'
          java-version: '17'
      - name: Build Application
        run: mvn clean install -Dskiptests
      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t shubham1807/university-app .
      - name: publish Image to DockerHub
        run: docker push shubham1807/university:latest
  deploy:
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from DockerHUb
        run: docker pull shubham1807/university-app:latest
      - name: Run MySQL-Container
        run: docker run -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE:university mysql
      - name: Run Application-Container
        run: docker run -d -p 8082:8082 --name university-app-container shubham1807/university-app:latest
